'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { AppShell } from '@/components/AppShell'
import { getGenLayerClient, type Submission } from '@/lib/genlayer-client'
export default function AppealPage({ params }: { params: { id: string } }) {
  const [item, setItem] = useState<Submission | null>(null); const [reason, setReason] = useState(''); const [url, setUrl] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { getGenLayerClient().getSubmission(params.id).then(setItem).catch((e) => setMessage(e.message)) }, [params.id])
  async function open(event: React.FormEvent) { event.preventDefault(); setBusy(true); const result = await getGenLayerClient().openAppeal(params.id, reason, url); setMessage(result.success ? 'Appeal opened. Resolve it after finalization.' : result.error || 'Appeal failed'); setBusy(false) }
  async function resolve() { setBusy(true); const result = await getGenLayerClient().resolveAppeal(params.id); setMessage(result.success ? 'Appeal verdict finalized.' : result.error || 'Appeal review failed'); setBusy(false) }
  return <AppShell title={`Appeal #${params.id}`} subtitle="A single appeal must add new, publicly readable evidence."><form onSubmit={open} className="mx-auto max-w-3xl assist-card rounded-[28px] p-7 md:p-10"><p className="text-sm font-bold">Current state: <span className="text-[#ff5b12]">{item?.status || 'Reading...'}</span></p>{item?.status === 'APPEAL_PENDING' ? <button type="button" onClick={resolve} disabled={busy} className="assist-btn-primary mt-6 h-14 w-full rounded-full font-black">{busy ? 'Reviewing...' : 'Resolve appeal with GenLayer'}</button> : <><label className="mt-7 block text-sm font-bold">Why the first decision should change</label><textarea required minLength={20} maxLength={900} value={reason} onChange={(e) => setReason(e.target.value)} className="assist-input mt-3 h-40 w-full resize-none rounded-[22px] p-5" /><label className="mt-5 block text-sm font-bold">New public evidence URL</label><input required type="url" value={url} onChange={(e) => setUrl(e.target.value)} className="assist-input mt-3 h-14 w-full rounded-full px-5" placeholder="https://..." /><button disabled={busy} className="assist-btn-primary mt-6 h-14 w-full rounded-full font-black">{busy ? 'Opening appeal...' : 'Open one-time appeal'}</button></>}{message && <p className="mt-4 rounded-[18px] bg-[#eef8fd] p-4 text-sm font-bold text-[#34566a]">{message}</p>}<Link href={`/app/request/${params.id}`} className="mt-5 block text-center text-sm font-black text-[#ff5b12]">Return to request</Link></form></AppShell>
}
